name: Generar Guardias

on:
  schedule:
    - cron: "0 8 25 * *" # corre el día 25 de cada mes a las 08:00 UTC
  workflow_dispatch: # permite correrlo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generar guardias
        run: node scripts/generarGuardias.js
        env:
          SHEET_URL: ${{ secrets.SHEET_URL }}

      - name: Commit & push cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/guardias.json
          git commit -m "🚀 Guardias generadas automáticamente"
          git push
